"""Mouse, keyboard, window/application, and description-based pointing control."""

from control.locator import (
    click_on_description,
    drag_between_descriptions,
    locate_target_on_screen,
    move_to_description,
)
from control.mouse_keyboard import (
    click_mouse,
    configure_pyautogui,
    drag_mouse,
    enable_windows_dpi_awareness,
    get_clipboard_text,
    get_computer_control_status,
    key_down,
    key_up,
    mouse_down,
    mouse_up,
    move_mouse,
    normalized_to_desktop,
    press_hotkey,
    press_key,
    scroll_mouse,
    type_text,
    wait_for_screen,
)
from control.windows import focus_window, launch_application, list_open_windows

__all__ = [
    "click_mouse",
    "click_on_description",
    "configure_pyautogui",
    "drag_between_descriptions",
    "drag_mouse",
    "enable_windows_dpi_awareness",
    "focus_window",
    "get_clipboard_text",
    "get_computer_control_status",
    "key_down",
    "key_up",
    "launch_application",
    "list_open_windows",
    "locate_target_on_screen",
    "mouse_down",
    "mouse_up",
    "move_mouse",
    "move_to_description",
    "normalized_to_desktop",
    "press_hotkey",
    "press_key",
    "scroll_mouse",
    "type_text",
    "wait_for_screen",
]
